### ISSUE TITLE
FeatureToggleGuard throws error because of missing Reflector

### ISSUE THREAD

**Issue by ionuts1704** [rorteg/nestjs-feature-toggle#31]
**Describe the bug**
FeatureToggleGuard throws error because of missing Reflector.

`[Nest] 86890  - 11/18/2022, 1:11:03 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at FeatureToggleGuard.<anonymous> (/node_modules/@rafaelortegabueno/nestjs-feature-toggle/dist/guards/feature-toggle.guard.js:35:47)
    at Generator.next (<anonymous>)`

**To Reproduce**
I was using exactly the same implementation as described in the docs section as well as the same nestjs versions -> `Enable/disable feature toggles with TypeScript Decorators`

```ts
@Module({
  imports: [
    FeatureToggleModule.register({
      dataSource: DataSourceEnum.MODULE_CONFIG,
      httpRequestContext: {
        enabled: true,
      },
      featureSettings: [
        {
          name: 'FEATURE_TEST_E2E',
          value: false,
          acceptHttpRequestContext: true,
        },
      ]
    }),
  ],
  providers: [
    {
      provide: APP_GUARD,
      useClass: FeatureToggleGuard,
    },
  ],
})
export class AppModule {}
```

**Expected behavior**
The Reflector should be available in the guard. I was able to make it work though by registering the guard through `app.useGlobalGuards`

```ts
const featureToggleService = new FeatureToggleService({
  dataSource: DataSourceEnum.MODULE_CONFIG,
  httpRequestContext: {
    enabled: true,
  },
  featureSettings: [
    {
      name: 'FEATURE_TEST_E2E',
      value: false,
      acceptHttpRequestContext: true,
    },
  ],
});

app.useGlobalGuards(new FeatureToggleGuard(reflector, featureToggleService));
```

```ts
@Module({
  imports: [
    FeatureToggleModule.register({
      dataSource: DataSourceEnum.MODULE_CONFIG,
      featureSettings: [],
    }),
  ],
  providers: [],
})
export class AppModule {}
```

**Comment by ryanchanplc** [comment]
Hi , same issue here.

Finally i found that their set up instruction is wrong.
We have to add `Scope.REQUEST` together with the APP_GUARD 

Hope they will update the instruction it accordingly

```
    {
      provide: APP_GUARD,
      useClass: FeatureToggleGuard,
      scope: Scope.REQUEST,
    }
```

**Comment by ran-j** [comment]
I will check that
